#!/bin/sh
# acq2106_init_gpio
source /usr/local/bin/acq400_init_gpio_common.sh

common_begin

# i2c gpio

CHIP1=$(basename $(echo /sys/bus/i2c/devices/1-0022/gpio/gpiochip*))
CHIP2=$(basename $(echo /sys/bus/i2c/devices/1-0023/gpio/gpiochip*))


let pin00=${CHIP1#gpiochip*}
let pin10=${CHIP2#gpiochip*}

echo +++ gpiochip 1-0022 $CHIP1 gpio $pin00 $pin01
echo +++ gpiochip 1-0023 $CHIP2 gpio $pin10 $pin11

mkdir -p /dev/gpio/CHIP1
let pin=$pin00
let ix=0
#        P000102030405060710111213141516172021222324252627
for dir in O O O O O O O O I O O O O O O O O O O O O I O O
do
	export_gpio $pin
	ln -s /sys/class/gpio/gpio$pin /dev/gpio/CHIP1/$(printf P%02o $ix)		
	[ "$dir" = "O" ] && setO gpio$pin
	let pin=$pin+1
	let ix=$ix+1
done


mkdir -p /dev/gpio/CHIP2
let pin=$pin10
let ix=0 
#        P000102030405060710111213141516172021222324252627
for dir in I I I I I I I I O O O O O O O O O O O O I I I I
do
	export_gpio $pin
	ln -s /sys/class/gpio/gpio$pin /dev/gpio/CHIP2/$(printf P%02o $ix)		
	[ "$dir" = "O" ] && setO gpio$pin
	let pin=$pin+1
	let ix=$ix+1
done	


nice daemon /usr/local/bin/heartbeat
# i2c gpio 



mkdir -p /dev/gpio/CLK/MB/
lnAH /dev/gpio/CHIP1/P00 /dev/gpio/CLK/OE_CLK1_ELF1
lnAH /dev/gpio/CHIP1/P01 /dev/gpio/CLK/OE_CLK1_ELF2
lnAH /dev/gpio/CHIP1/P02 /dev/gpio/CLK/OE_CLK1_ELF3
lnAH /dev/gpio/CHIP1/P03 /dev/gpio/CLK/OE_CLK1_ELF4
lnAH /dev/gpio/CHIP1/P04 /dev/gpio/CLK/OE_CLK1_ELF5
lnAH /dev/gpio/CHIP1/P05 /dev/gpio/CLK/OE_CLK1_ELF6
lnAH /dev/gpio/CHIP1/P06 /dev/gpio/CLK/OE_CLK1_ZYNQ
mkdir -p /dev/gpio/LED
lnAH /dev/gpio/CHIP1/P07 /dev/gpio/LED/MGT1_G
lnAL /dev/gpio/CHIP1/P10 /dev/gpio/MGT_PRESENT
lnAH /dev/gpio/CHIP1/P11 /dev/gpio/LED/MGT1_R
lnAH /dev/gpio/CHIP1/P12 /dev/gpio/LED/MGT2_G
lnAH /dev/gpio/CHIP1/P13 /dev/gpio/LED/MGT2_R
lnAH /dev/gpio/CHIP1/P14 /dev/gpio/LED/MGT3_G
lnAH /dev/gpio/CHIP1/P15 /dev/gpio/LED/MGT3_R
lnAH /dev/gpio/CHIP1/P16 /dev/gpio/LED/MGT4_G
lnAH /dev/gpio/CHIP1/P17 /dev/gpio/LED/MGT4_R

lnAH /dev/gpio/CHIP1/P20 /dev/gpio/OE_CLK1_SYNC
lnAH /dev/gpio/CHIP1/P21 /dev/gpio/FP_SYNC_DIR_OUT
lnAH /dev/gpio/CHIP1/P22 /dev/gpio/FP_IO_DIR_OUT
lnAH /dev/gpio/CHIP1/P23 /dev/gpio/SYNC_IN_GPIO_OUT
lnAH /dev/gpio/CHIP1/P24 /dev/gpio/SYNC_OUT_GPIO_OUT
lnAL /dev/gpio/CHIP1/P25 /dev/gpio/SYNC_CABLE_DET
lnAH /dev/gpio/CHIP1/P26 /dev/gpio/LED/MGT5_G
lnAH /dev/gpio/CHIP1/P27 /dev/gpio/LED/MGT5_R

echo 1 > /dev/gpio/SYNC_OUT_GPIO_OUT

lnAL /dev/gpio/CHIP2/P00	/dev/gpio/fmc1_present
lnAL /dev/gpio/CHIP2/P01	/dev/gpio/fmc2_present
lnAL /dev/gpio/CHIP2/P02	/dev/gpio/fmc3_present
lnAL /dev/gpio/CHIP2/P03	/dev/gpio/fmc4_present
lnAL /dev/gpio/CHIP2/P04	/dev/gpio/fmc5_present
lnAL /dev/gpio/CHIP2/P05	/dev/gpio/fmc6_present
lnAL /dev/gpio/CHIP2/P06 	/dev/gpio/15VP_PGD
lnAL /dev/gpio/CHIP2/P07	/dev/gpio/15VN_PGD

lnALO /dev/gpio/CHIP2/P10	/dev/gpio/CLK/ZCLK_OE
lnALO /dev/gpio/CHIP2/P11	/dev/gpio/CLK/DIST_CLK_HDMI  # Not CLK1
lnALO /dev/gpio/CHIP2/P12	/dev/gpio/CLK/OSC_X_OE
lnALO /dev/gpio/CHIP2/P13	/dev/gpio/CLK/OSC_X_CLK_OE
lnALO /dev/gpio/CHIP2/P14	/dev/gpio/CLK/FP_CLK_OE
lnALO /dev/gpio/CHIP2/P15	/dev/gpio/CLK/FP_OE
lnALO /dev/gpio/CHIP2/P16	/dev/gpio/CLK/Si570_OE
lnALO /dev/gpio/CHIP2/P17	/dev/gpio/15VA_EN


lnALO /dev/gpio/CHIP2/P20	/dev/gpio/LED/CLK_G
lnALO /dev/gpio/CHIP2/P21	/dev/gpio/LED/CLK_R
lnALO /dev/gpio/CHIP2/P22	/dev/gpio/LED/TRG_G
lnALO /dev/gpio/CHIP2/P23	/dev/gpio/LED/TRG_R

lnAH /dev/gpio/CHIP2/P24/	/dev/gpio/IS_ACQ2206
lnAL /dev/gpio/CHIP2/P25/	/dev/gpio/IS_REVB
lnAL /dev/gpio/CHIP2/P26/	/dev/gpio/IS_ACQ2006
lnAL /dev/gpio/CHIP2/P27/	/dev/gpio/IS_RES


common_end
source /usr/local/bin/acq2006_init_gpio_common.sh

echo "++ acq2006b_init_gpio done"

