#!/bin/sh
# acq2106_init_gpio
source /usr/local/bin/acq400_init_gpio_common.sh

common_begin

if [ ! -e /sys/bus/i2c/devices/1-0022/gpio/gpiochip* ]; then
	echo I2C ERROR: unable to continue
	PS1="$PS1 I2C FAIL #" /bin/sh
fi

# i2c gpio

# si5326
mkdir -p /dev/gpio/CLK
zgpio0=$(get_zynq_gpio0)
export_gpio_value_ln $(($zgpio0+11)) /dev/gpio/CLK/LOL
export_gpio_value_ln $(($zgpio0+14)) /dev/gpio/CLK/C1B
export_gpio_value_ln $(($zgpio0+15)) /dev/gpio/CLK/C2B


# main GPIO
CHIP1=$(basename $(echo /sys/bus/i2c/devices/1-0022/gpio/gpiochip*))
CHIP2=$(basename $(echo /sys/bus/i2c/devices/1-0023/gpio/gpiochip*))


let pin00=${CHIP1#gpiochip*}
let pin10=${CHIP2#gpiochip*}

echo +++ gpiochip 1-0022 $CHIP1 gpio $pin00 $pin01
echo +++ gpiochip 1-0023 $CHIP2 gpio $pin10 $pin11

mkdir -p /dev/gpio/CHIP1
let pin=$pin00
let ix=0
#        P000102030405060710111213141516172021222324252627
for dir in O O O O O O O O I O O O O O O O O O O O O I O O
do
	export_gpio $pin
	ln -s /sys/class/gpio/gpio$pin /dev/gpio/CHIP1/$(printf P%02o $ix)		
	[ "$dir" = "O" ] && setO gpio$pin
	let pin=$pin+1
	let ix=$ix+1
done


mkdir -p /dev/gpio/CHIP2
let pin=$pin10
let ix=0 
#        P000102030405060710111213141516172021222324252627
for dir in I I I I I I I I O O O O O O O O O O O O I I I I
do
	export_gpio $pin
	ln -s /sys/class/gpio/gpio$pin /dev/gpio/CHIP2/$(printf P%02o $ix)		
	[ "$dir" = "O" ] && setO gpio$pin
	let pin=$pin+1
	let ix=$ix+1
done	

# i2c gpio 

source /usr/local/bin/acq2106_init_gpio_common.sh

if [ "x$FPCHIP1" != "x" ]; then
	echo +++ FPCHIP1 FOUND $FPCHIP1
	mkdir /dev/gpio/FPCHIP1
	let p00=${FPCHIP1#gpiochip*}
	for pin in 8 9 10 11 15; do
		gp=$(($p00+$pin))
		export_gpio_value_ln ${gp} /dev/gpio/FPCHIP1/$(printf %02d $pin)
		setO gpio${gp}
	done
	for pin in 12 13 14; do
		gp=$(($p00+$pin)
		export_gpio_value_ln ${gp} /dev/gpio/FPCHIP1/$(printf %02d $pin)
	done
	echo +++ FP MODEL CODE $(cat /dev/gpio/FPCHIP1/1[234])
fi

if [ "x$FPCHIP2 != "x" ; then
	echo +++ FPCHIP2 FOUND $FPCHIP2
	mkdir /dev/gpio/FPCHIP2
	let p00=${FPCHIP1#gpiochip*}
	let p15=$(($p00
	for pin in $(seq 0 15); do
		gp=$(($p00+$pin))
		export_gpio_value_ln ${gp} /dev/gpio/FPCHIP2/$(printf %02d $pin)
		setO gpio${gp}
	done
fi

mkdir -p /dev/gpio/CLK/MB/
lnAH /dev/gpio/CHIP1/P00 /dev/gpio/CLK/OE_CLK1_ELF1
lnAH /dev/gpio/CHIP1/P01 /dev/gpio/CLK/OE_CLK1_ELF2
lnAH /dev/gpio/CHIP1/P02 /dev/gpio/CLK/OE_CLK1_ELF3
lnAH /dev/gpio/CHIP1/P03 /dev/gpio/CLK/OE_CLK1_ELF4
lnAH /dev/gpio/CHIP1/P04 /dev/gpio/CLK/OE_CLK1_ELF5
lnAH /dev/gpio/CHIP1/P05 /dev/gpio/CLK/OE_CLK1_ELF6
lnAH /dev/gpio/CHIP1/P06 /dev/gpio/CLK/OE_CLK1_ZYNQ
mkdir -p /dev/gpio/LED
lnAL /dev/gpio/CHIP1/P07 /dev/gpio/LED/MGT5_G
lnAL /dev/gpio/CHIP1/P10 /dev/gpio/MGT_PRESENT
lnAL /dev/gpio/CHIP1/P11 /dev/gpio/LED/MGT5_R
lnAL /dev/gpio/CHIP1/P12 /dev/gpio/LED/MGT4_G
lnAL /dev/gpio/CHIP1/P13 /dev/gpio/LED/MGT4_R
lnAL /dev/gpio/CHIP1/P14 /dev/gpio/LED/MGT3_G
lnAL /dev/gpio/CHIP1/P15 /dev/gpio/LED/MGT3_R
lnAL /dev/gpio/CHIP1/P16 /dev/gpio/LED/MGT2_G
lnAL /dev/gpio/CHIP1/P17 /dev/gpio/LED/MGT2_R

lnAH /dev/gpio/CHIP1/P20 /dev/gpio/OE_CLK1_SYNC
lnAH /dev/gpio/CHIP1/P21 /dev/gpio/FP_SYNC_DIR_OUT
lnAH /dev/gpio/CHIP1/P22 /dev/gpio/FP_IO_DIR_OUT
lnAH /dev/gpio/CHIP1/P23 /dev/gpio/SYNC_IN_GPIO_OUT
lnAH /dev/gpio/CHIP1/P24 /dev/gpio/SYNC_OUT_GPIO_OUT
lnAL /dev/gpio/CHIP1/P25 /dev/gpio/SYNC_CABLE_DET
lnAL /dev/gpio/CHIP1/P26 /dev/gpio/LED/MGT1_G
lnAL /dev/gpio/CHIP1/P27 /dev/gpio/LED/MGT1_R

echo 1 > /dev/gpio/SYNC_OUT_GPIO_OUT

lnAL /dev/gpio/CHIP2/P00	/dev/gpio/fmc1_present
lnAL /dev/gpio/CHIP2/P01	/dev/gpio/fmc2_present
lnAL /dev/gpio/CHIP2/P02	/dev/gpio/fmc3_present
lnAL /dev/gpio/CHIP2/P03	/dev/gpio/fmc4_present
lnAL /dev/gpio/CHIP2/P04	/dev/gpio/fmc5_present
lnAL /dev/gpio/CHIP2/P05	/dev/gpio/fmc6_present
lnAL /dev/gpio/CHIP2/P06 	/dev/gpio/15VP_PGD
lnAL /dev/gpio/CHIP2/P07	/dev/gpio/15VN_PGD

lnALO /dev/gpio/CHIP2/P10	/dev/gpio/CLK/ZCLK_OE
lnALO /dev/gpio/CHIP2/P11	/dev/gpio/CLK/DIST_CLK_HDMI  # Not CLK1
lnALO /dev/gpio/CHIP2/P12	/dev/gpio/CLK/OSC_X_OE
lnALO /dev/gpio/CHIP2/P13	/dev/gpio/CLK/OSC_X_CLK_OE
lnALO /dev/gpio/CHIP2/P14	/dev/gpio/CLK/FP_CLK_OE
lnALO /dev/gpio/CHIP2/P15	/dev/gpio/CLK/FP_OE
lnALO /dev/gpio/CHIP2/P16	/dev/gpio/CLK/Si570_OE
lnALO /dev/gpio/CHIP2/P17	/dev/gpio/15VA_EN

if [ "x$FPCHIP1" = "x" ]; then 
lnALO /dev/gpio/CHIP2/P20	/dev/gpio/LED/CLK_G
lnALO /dev/gpio/CHIP2/P21	/dev/gpio/LED/CLK_R
lnALO /dev/gpio/CHIP2/P22	/dev/gpio/LED/TRG_G
lnALO /dev/gpio/CHIP2/P23	/dev/gpio/LED/TRG_R
else
lnALO /dev/gpio/FPCHIP1/P08	/dev/gpio/LED/CLK_G
lnALO /dev/gpio/FPCHIP1/P09	/dev/gpio/LED/CLK_R
lnALO /dev/gpio/FPCHIP1/P10	/dev/gpio/LED/TRG_G
lnALO /dev/gpio/FPCHIP1/P11	/dev/gpio/LED/TRG_R	
fi

lnAH /dev/gpio/CHIP2/P24/	/dev/gpio/IS_ACQ2206
lnAL /dev/gpio/CHIP2/P25/	/dev/gpio/IS_REVB
lnAH /dev/gpio/CHIP2/P26/	/dev/gpio/IS_ACQ2006
lnAL /dev/gpio/CHIP2/P27/	/dev/gpio/IS_RES


echo "setting DIST_CLK_HDMI .. Si5326 is the ONLY valid input.."
set.sys /dev/gpio/CLK/DIST_CLK_HDMI 1




MODEL=$(cat /proc/device-tree/chosen/model)
if [ "{$MODEL#*d37}" != "$MODEL" ]; then
	source /usr/local/CARE/acq2106_init_gpio.sh
elif [ "x$FPCHIP2" != "x" ]; then
	+++ init FPLEDS 
	init_acq2106_leds $(getchip 1-0062)
else
	+++ init BPLEDS
	init_acq2106_leds $(getchip 1-0060)
fi
common_end
echo "++ acq2106b_init_gpio done"

