#!/bin/sh

mkdir -p /dev/gpio
cd /sys/class/gpio

setO() {
	echo out >$1/direction
}
setAL() {
	echo 1 >$1/active_low
}
mkln() {
	ln -s $PWD/$1/value /dev/gpio/$2
}

for pin in $(seq 216 255)
do
	echo $pin >export
done


for pin in $(seq 240 247) $(seq 232 239)
do
	setO gpio$pin
done

mkdir -p /dev/gpio/CLK/RDW
mkln gpio240 CLK/RDW/R6
mkln gpio241 CLK/RDW/R5
mkln gpio242 CLK/RDW/R4
mkln gpio243 CLK/RDW/R3
mkln gpio244 CLK/RDW/R2
mkln gpio245 CLK/RDW/R1
mkln gpio246 CLK/RDW/R0

mkdir /dev/gpio/CLK/FDW
mkln gpio247 CLK/FDW/F6
mkln gpio232 CLK/FDW/F5
mkln gpio233 CLK/FDW/F4
mkln gpio234 CLK/FDW/F3
mkln gpio235 CLK/FDW/F2
mkln gpio236 CLK/FDW/F1
mkln gpio237 CLK/FDW/F0

mkdir /dev/gpio/CLK/ODW
mkln gpio238 CLK/ODW/S1
mkln gpio239 CLK/ODW/S0


let site=0; while [ $site -lt 6 ]; do
	let gpio=248+$site
	GPIO=gpio${gpio}
	setAL $GPIO; mkln ${GPIO} fmc${site}_present
	let site=$site+1
done

setAL gpio254; mkln gpio254 15VP_PGD
setAL gpio255; mkln gpio255 15VN_PGD


for pin in $(seq 224 231) $(seq 216 219)
do
	setO gpio${pin}
done

		mkln gpio224 ICS_CLK2_OE
setAL gpio225; 	mkln gpio225 OSC_X_OE
setAL gpio226;	mkln gpio226 OSC_X_CLK_OE
setAL gpio227;	mkln gpio227 FP_CLK_OE
setAL gpio228;	mkln gpio228 FP_OE
		mkln gpio229 Si570_OE
		mkln gpio230 15VA_EN
		mkln gpio231 PSU_SYNC_CLK_OE

setAL gpio216;	mkln gpio216 LED_G_CLK
setAL gpio217;	mkln gpio217 LED_R_CLK
setAL gpio218;	mkln gpio218 LED_G_TRG
setAL gpio219; 	mkln gpio219 LED_R_TRG

		mkln gpio220 BV_EE
		mkln gpio221 BV_RSV1
		mkln gpio222 BV_RSV2
		mkln gpio222 JTAG14_ALL

# OK, this isn't gpio, but it's handy to put it here:

mkdir -p /dev/hwmon0
ln -s /sys/class/hwmon/hwmon0/device/temp1_input /dev/hwmon0/temp
ln -s /sys/class/hwmon/hwmon0/device/in1_input	 /dev/hwmon0/15VA_N
ln -s /sys/class/hwmon/hwmon0/device/in2_input	 /dev/hwmon0/15VA_P
ln -s /sys/class/hwmon/hwmon0/device/in3_input	 /dev/hwmon0/5V_P
ln -s /sys/class/hwmon/hwmon0/device/in4_input	 /dev/hwmon0/VADJ


