#!/bin/sh

VERBOSE=${1:-0}

set_lamp() {
	if [ $VERBOSE -gt 0 ]; then
		echo set.sys /dev/gpio/LED/MGT${1}_${2}
	fi
	set.sys dev/gpio/LED/MGT${1}_${2}
	if [ $VERBOSE -gt 1 ]; then
		echo -n READY>;read stuff
	fi 	
}

for S in 1 2 3 4 5
do
   for RG in R G
   do
   	set_lamp $S $R 1
   	usleep .3
   	set_lamp $S $R 0
   done
done
   