#!/usr/local/bin/expect

proc sfp_decode {eeprom} {
	set fp [open $eeprom r]
	set sid [read $fp]
	close $fp
#             1234567890	
	puts "    Vendor: [string range $sid 20 35]"
	puts "        PN: [string range $sid 40 55]"
	puts "        SN: [string range $sid 68 83]"
	puts "-------------------------------------"
}


foreach arg $::argv {
	sfp_decode $arg
}

